apiVersion: apps/v1
kind: Deployment
metadata:
  name: applications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applications-service
  template:
    metadata:
      labels:
        app: applications-service
    spec:
      containers:
        - name: applications-container
          image: <your-ecr-url>/applications-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "jobportal"
---
apiVersion: v1
kind: Service
metadata:
  name: applications-service
spec:
  selector:
    app: applications-service
  ports:
    - port: 80
      targetPort: 5000
